version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
