---
pause:
  fields:
    address:
      example: "localhost"
      default: "localhost"
      required: true
      selector:
        text:
    slot:
      example: "01"
      required: false
      selector:
        text:

unpause:
  fields:
    address:
      example: "localhost"
      default: "localhost"
      required: true
      selector:
        text:
    slot:
      example: "01"
      required: false
      selector:
        text:

shutdown:
  fields:
    address:
      example: "localhost"
      default: "localhost"
      required: true
      selector:
        text:

request_work_server_assignment:
  fields:
    address:
      example: "localhost"
      default: "localhost"
      required: true
      selector:
        text:

set_power_level:
  fields:
    address:
      example: "localhost"
      default: "localhost"
      required: true
      selector:
        text:
    power_level:
      example: "LIGHT"
      default: "FULL"
      required: true
      selector:
        select:
          options:
            - "LIGHT"
            - "MEDIUM"
            - "FULL"

send_command:
  fields:
    address:
      example: "localhost"
      default: "localhost"
      required: true
      selector:
        text:
    command:
      example: "slot-info"
      required: true
      selector:
        text:
